import { useEffect, useState } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { Company } from "./api/companies";
import { Deal } from "./api/deals";

const Home: NextPage = () => {
  const fetchCompanies = async () => {
    const response = await fetch("/api/companies");
    return await response.json();
  };

  const fetchDeals = async () => {
    const response = await fetch("/api/deals");
    return await response.json();
  };

  const [companies, setCompanies] = useState<Company[]>([]);
  const [deals, setDeals] = useState<Deal[]>([]);

  useEffect(() => {
    fetchCompanies().then((data) => {
      setCompanies(data);
    });
    fetchDeals().then((data) => {
      setDeals(data);
    });
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Foundamental Challenge</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Foundamental Challenge</h1>

        <div>
          {companies?.map((company) => (
            <div className={styles.company} key={company.company_id}>
              <h2>{company.name}</h2>
              <h3>Description:</h3>
              <p>{company.description}</p>
              <h3>Country:</h3>
              <p>{company.country}</p>
              <h3>Founding Date:</h3>
              <p>{company.founding_date}</p>
              <h3>Deals:</h3>
              {deals?.filter((deal) => deal.company_id === company.company_id).map((deal) => (
                <div className={styles.deal} key={deal.id}>
                  <h4>Deal Funding Amount:</h4>
                  <p>${deal.funding_amount}</p>
                  <h4>Deal Funding Round:</h4>
                  <p>{deal.funding_round}</p>
                  <h4>Deal Date:</h4>
                  <p>{deal.date}</p>
                </div>
                )
              )}
            </div>
          ))}
        </div>
      </main>
    </div>
  );
};

export default Home;
